package UI;

import Core.Transaction;
import User.ManageUser;
import User.UserSession;
import javax.swing.JOptionPane;

/**
 *
 * @author Mellisa
 */
public class Investment extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Investment.class.getName());

    /**
     * Creates new form Investment
     */
    public Investment() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void loadData(){
        UserSession.getUserInformation();
        
        String balance = String.format("%.2f",UserSession.getCurrentUserBalance());
        String investment = String.format("%.2f",UserSession.getCurrentInvestmentBalance());
        
        lBalance.setText(balance);
        lInvestment.setText(investment);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new javax.swing.JPanel();
        panelNavigation = new javax.swing.JPanel();
        lHomeLogo = new javax.swing.JLabel();
        lHomeInfo = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        lSearchNav = new javax.swing.JLabel();
        panelInvestment = new javax.swing.JPanel();
        lProfileNav = new javax.swing.JLabel();
        panelProfile = new javax.swing.JPanel();
        lHomeNav = new javax.swing.JLabel();
        refreshIcon = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        lSimulateTime = new javax.swing.JLabel();
        lInvestment = new javax.swing.JLabel();
        lInvestmentText = new javax.swing.JLabel();
        lBalanceText = new javax.swing.JLabel();
        lBalance = new javax.swing.JLabel();
        tfAmount = new javax.swing.JTextField();
        btnConfirmInvestment = new javax.swing.JButton();
        btnHour = new javax.swing.JButton();
        btnSeeRate = new javax.swing.JButton();
        btnDay = new javax.swing.JButton();
        btnWeek = new javax.swing.JButton();
        btnMonth = new javax.swing.JButton();
        btnYear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Investment");
        setMaximumSize(new java.awt.Dimension(850, 600));
        setMinimumSize(new java.awt.Dimension(850, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 600));

        panelBG.setBackground(new java.awt.Color(51, 51, 51));
        panelBG.setLayout(null);

        panelNavigation.setBackground(new java.awt.Color(102, 102, 102));
        panelNavigation.setLayout(null);

        lHomeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Investment Logo.png"))); // NOI18N
        panelNavigation.add(lHomeLogo);
        lHomeLogo.setBounds(20, 10, 60, 60);

        lHomeInfo.setBackground(new java.awt.Color(255, 255, 255));
        lHomeInfo.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        lHomeInfo.setForeground(new java.awt.Color(255, 255, 255));
        lHomeInfo.setText("Investment");
        panelNavigation.add(lHomeInfo);
        lHomeInfo.setBounds(90, 30, 280, 50);

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));
        panelSearch.setForeground(new java.awt.Color(255, 255, 255));

        lSearchNav.setBackground(new java.awt.Color(255, 255, 255));
        lSearchNav.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lSearchNav.setForeground(new java.awt.Color(51, 51, 51));
        lSearchNav.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSearchNav.setText("Search");
        lSearchNav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lSearchNav.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lSearchNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSearchNavMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lSearchNavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lSearchNavMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lSearchNav, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lSearchNav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelNavigation.add(panelSearch);
        panelSearch.setBounds(730, 50, 83, 30);

        panelInvestment.setBackground(new java.awt.Color(255, 255, 255));

        lProfileNav.setBackground(new java.awt.Color(255, 255, 255));
        lProfileNav.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lProfileNav.setForeground(new java.awt.Color(51, 51, 51));
        lProfileNav.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lProfileNav.setText("Profile");
        lProfileNav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lProfileNav.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lProfileNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lProfileNavMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lProfileNavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lProfileNavMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInvestmentLayout = new javax.swing.GroupLayout(panelInvestment);
        panelInvestment.setLayout(panelInvestmentLayout);
        panelInvestmentLayout.setHorizontalGroup(
            panelInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvestmentLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lProfileNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInvestmentLayout.setVerticalGroup(
            panelInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lProfileNav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelNavigation.add(panelInvestment);
        panelInvestment.setBounds(600, 50, 120, 30);

        panelProfile.setBackground(new java.awt.Color(255, 255, 255));

        lHomeNav.setBackground(new java.awt.Color(255, 255, 255));
        lHomeNav.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lHomeNav.setForeground(new java.awt.Color(51, 51, 51));
        lHomeNav.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lHomeNav.setText("Home");
        lHomeNav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lHomeNav.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lHomeNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lHomeNavMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lHomeNavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lHomeNavMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lHomeNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lHomeNav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelNavigation.add(panelProfile);
        panelProfile.setBounds(500, 50, 90, 30);

        panelBG.add(panelNavigation);
        panelNavigation.setBounds(0, 0, 850, 80);

        refreshIcon.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        refreshIcon.setForeground(new java.awt.Color(255, 255, 255));
        refreshIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh Icon.png"))); // NOI18N
        refreshIcon.setText("Refresh");
        refreshIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshIconMouseClicked(evt);
            }
        });
        panelBG.add(refreshIcon);
        refreshIcon.setBounds(0, 80, 80, 30);

        logoutIcon.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        logoutIcon.setForeground(new java.awt.Color(255, 255, 255));
        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout Logo.png"))); // NOI18N
        logoutIcon.setText("Log-out");
        logoutIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutIconMouseClicked(evt);
            }
        });
        panelBG.add(logoutIcon);
        logoutIcon.setBounds(770, 80, 80, 30);

        lSimulateTime.setBackground(new java.awt.Color(255, 255, 255));
        lSimulateTime.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lSimulateTime.setForeground(new java.awt.Color(255, 255, 255));
        lSimulateTime.setText("Simulate Time");
        panelBG.add(lSimulateTime);
        lSimulateTime.setBounds(610, 280, 140, 30);

        lInvestment.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lInvestment.setForeground(new java.awt.Color(255, 255, 255));
        lInvestment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lInvestment.setText("00.00");
        panelBG.add(lInvestment);
        lInvestment.setBounds(270, 180, 550, 60);

        lInvestmentText.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lInvestmentText.setForeground(new java.awt.Color(255, 255, 255));
        lInvestmentText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lInvestmentText.setText("Investment:");
        panelBG.add(lInvestmentText);
        lInvestmentText.setBounds(40, 180, 220, 60);

        lBalanceText.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lBalanceText.setForeground(new java.awt.Color(255, 255, 255));
        lBalanceText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lBalanceText.setText("Balance:");
        panelBG.add(lBalanceText);
        lBalanceText.setBounds(40, 120, 170, 60);

        lBalance.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lBalance.setForeground(new java.awt.Color(255, 255, 255));
        lBalance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lBalance.setText("00.00");
        panelBG.add(lBalance);
        lBalance.setBounds(210, 120, 610, 60);

        tfAmount.setBackground(new java.awt.Color(102, 102, 102));
        tfAmount.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        tfAmount.setForeground(new java.awt.Color(255, 255, 255));
        tfAmount.setText("00.00");
        panelBG.add(tfAmount);
        tfAmount.setBounds(40, 310, 262, 28);

        btnConfirmInvestment.setBackground(new java.awt.Color(102, 102, 102));
        btnConfirmInvestment.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnConfirmInvestment.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmInvestment.setText("Confirm Investment");
        btnConfirmInvestment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmInvestmentActionPerformed(evt);
            }
        });
        panelBG.add(btnConfirmInvestment);
        btnConfirmInvestment.setBounds(40, 390, 262, 29);

        btnHour.setBackground(new java.awt.Color(102, 102, 102));
        btnHour.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnHour.setForeground(new java.awt.Color(255, 255, 255));
        btnHour.setText("Hour");
        btnHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHourActionPerformed(evt);
            }
        });
        panelBG.add(btnHour);
        btnHour.setBounds(540, 310, 266, 29);

        btnSeeRate.setBackground(new java.awt.Color(102, 102, 102));
        btnSeeRate.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnSeeRate.setForeground(new java.awt.Color(255, 255, 255));
        btnSeeRate.setText("See Rate");
        panelBG.add(btnSeeRate);
        btnSeeRate.setBounds(40, 350, 262, 29);

        btnDay.setBackground(new java.awt.Color(102, 102, 102));
        btnDay.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnDay.setForeground(new java.awt.Color(255, 255, 255));
        btnDay.setText("Day");
        btnDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDayActionPerformed(evt);
            }
        });
        panelBG.add(btnDay);
        btnDay.setBounds(540, 350, 266, 29);

        btnWeek.setBackground(new java.awt.Color(102, 102, 102));
        btnWeek.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnWeek.setForeground(new java.awt.Color(255, 255, 255));
        btnWeek.setText("Week");
        btnWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeekActionPerformed(evt);
            }
        });
        panelBG.add(btnWeek);
        btnWeek.setBounds(540, 390, 266, 29);

        btnMonth.setBackground(new java.awt.Color(102, 102, 102));
        btnMonth.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnMonth.setForeground(new java.awt.Color(255, 255, 255));
        btnMonth.setText("Month");
        btnMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthActionPerformed(evt);
            }
        });
        panelBG.add(btnMonth);
        btnMonth.setBounds(540, 430, 266, 29);

        btnYear.setBackground(new java.awt.Color(102, 102, 102));
        btnYear.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnYear.setForeground(new java.awt.Color(255, 255, 255));
        btnYear.setText("Year");
        btnYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearActionPerformed(evt);
            }
        });
        panelBG.add(btnYear);
        btnYear.setBounds(540, 470, 266, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(864, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lSearchNavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSearchNavMouseEntered
        lSearchNav.setText("<html><u>" + "Search" + "<u/><html>");
    }//GEN-LAST:event_lSearchNavMouseEntered

    private void lSearchNavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSearchNavMouseExited
        lSearchNav.setText("Search");
    }//GEN-LAST:event_lSearchNavMouseExited

    private void lProfileNavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProfileNavMouseEntered
        lProfileNav.setText("<html><u>" + "Profile" + "<u/><html>");
    }//GEN-LAST:event_lProfileNavMouseEntered

    private void lProfileNavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProfileNavMouseExited
        lProfileNav.setText("Profile");
    }//GEN-LAST:event_lProfileNavMouseExited

    private void lHomeNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lHomeNavMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lHomeNavMouseClicked

    private void lHomeNavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lHomeNavMouseEntered
        lHomeNav.setText("<html><u>" + "Home" + "<u/><html>");
    }//GEN-LAST:event_lHomeNavMouseEntered

    private void lHomeNavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lHomeNavMouseExited
        lHomeNav.setText("Home");
    }//GEN-LAST:event_lHomeNavMouseExited

    private void btnHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHourActionPerformed

    private void btnDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDayActionPerformed

    private void btnWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWeekActionPerformed

    private void btnMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMonthActionPerformed

    private void btnYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYearActionPerformed

    private void lProfileNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProfileNavMouseClicked
        // TODO add your handling code here:
        Profile profile = new Profile();
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lProfileNavMouseClicked

    private void lSearchNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSearchNavMouseClicked
        // TODO add your handling code here:
        Search search = new Search();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lSearchNavMouseClicked

    private void refreshIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshIconMouseClicked
        loadData();
    }//GEN-LAST:event_refreshIconMouseClicked

    private void logoutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutIconMouseClicked
        UserSession.logOut();
        this.dispose();
    }//GEN-LAST:event_logoutIconMouseClicked

    private void btnConfirmInvestmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmInvestmentActionPerformed
        // TODO add your handling code here:
        
        if (!tfAmount.getText().trim().isEmpty()){
            try {
                
                double amount = Double.parseDouble(tfAmount.getText().trim());
                
                Transaction transac = new Transaction();
        
                transac.investMoney(amount);
            
            } catch (NumberFormatException e) {
                String errorMessage = "Invalid input, only numerical values are allowed.";
                JOptionPane.showMessageDialog(null, errorMessage, "Deposit Failed", JOptionPane.ERROR_MESSAGE);
                tfAmount.setText("00.00");
                return;
            }
        }
    }//GEN-LAST:event_btnConfirmInvestmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Investment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmInvestment;
    private javax.swing.JButton btnDay;
    private javax.swing.JButton btnHour;
    private javax.swing.JButton btnMonth;
    private javax.swing.JButton btnSeeRate;
    private javax.swing.JButton btnWeek;
    private javax.swing.JButton btnYear;
    private javax.swing.JLabel lBalance;
    private javax.swing.JLabel lBalanceText;
    private javax.swing.JLabel lHomeInfo;
    private javax.swing.JLabel lHomeLogo;
    private javax.swing.JLabel lHomeNav;
    private javax.swing.JLabel lInvestment;
    private javax.swing.JLabel lInvestmentText;
    private javax.swing.JLabel lProfileNav;
    private javax.swing.JLabel lSearchNav;
    private javax.swing.JLabel lSimulateTime;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JPanel panelBG;
    private javax.swing.JPanel panelInvestment;
    private javax.swing.JPanel panelNavigation;
    private javax.swing.JPanel panelProfile;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JLabel refreshIcon;
    private javax.swing.JTextField tfAmount;
    // End of variables declaration//GEN-END:variables
}
