package UI;

import PaymentMethods.*;
import User.UserSession;
import javax.swing.JOptionPane;

/**
 *
 * @author Mellisa
 */
public class Pay extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pay.class.getName());

    /**
     * Creates new form Pay
     */
    public Pay() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupPay = new javax.swing.ButtonGroup();
        panelBackground = new javax.swing.JPanel();
        lBalance = new javax.swing.JLabel();
        lDepositAmount1 = new javax.swing.JLabel();
        lDepositAmount = new javax.swing.JLabel();
        tfPayAmount = new javax.swing.JTextField();
        btnConfirmDeposit = new javax.swing.JButton();
        rbGeneric = new javax.swing.JRadioButton();
        rbPaypal = new javax.swing.JRadioButton();
        rbCard = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pay");
        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));

        panelBackground.setBackground(new java.awt.Color(51, 51, 51));
        panelBackground.setLayout(null);

        lBalance.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lBalance.setForeground(new java.awt.Color(255, 255, 255));
        lBalance.setText("Current Balance: ");
        panelBackground.add(lBalance);
        lBalance.setBounds(10, 40, 770, 40);

        lDepositAmount1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lDepositAmount1.setForeground(new java.awt.Color(255, 255, 255));
        lDepositAmount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDepositAmount1.setText("Pay Using:");
        panelBackground.add(lDepositAmount1);
        lDepositAmount1.setBounds(340, 160, 150, 40);

        lDepositAmount.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lDepositAmount.setForeground(new java.awt.Color(255, 255, 255));
        lDepositAmount.setText("Pay Amount:");
        panelBackground.add(lDepositAmount);
        lDepositAmount.setBounds(80, 100, 150, 40);

        tfPayAmount.setBackground(new java.awt.Color(102, 102, 102));
        tfPayAmount.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        tfPayAmount.setForeground(new java.awt.Color(255, 255, 255));
        tfPayAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPayAmountKeyReleased(evt);
            }
        });
        panelBackground.add(tfPayAmount);
        tfPayAmount.setBounds(240, 100, 470, 40);

        btnConfirmDeposit.setBackground(new java.awt.Color(102, 102, 102));
        btnConfirmDeposit.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnConfirmDeposit.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmDeposit.setText("Confirm Pay");
        btnConfirmDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmDepositActionPerformed(evt);
            }
        });
        panelBackground.add(btnConfirmDeposit);
        btnConfirmDeposit.setBounds(240, 290, 350, 40);

        groupPay.add(rbGeneric);
        rbGeneric.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        rbGeneric.setForeground(new java.awt.Color(255, 255, 255));
        rbGeneric.setText(" Generic Method");
        panelBackground.add(rbGeneric);
        rbGeneric.setBounds(70, 200, 200, 27);

        groupPay.add(rbPaypal);
        rbPaypal.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        rbPaypal.setForeground(new java.awt.Color(255, 255, 255));
        rbPaypal.setText(" Paypal Method");
        panelBackground.add(rbPaypal);
        rbPaypal.setBounds(330, 200, 170, 27);

        groupPay.add(rbCard);
        rbCard.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        rbCard.setForeground(new java.awt.Color(255, 255, 255));
        rbCard.setText(" Card Method");
        panelBackground.add(rbCard);
        rbCard.setBounds(590, 200, 160, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(814, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(){
        UserSession.getUserInformation();
        
        String balance = String.format("Current Balance: "+"%.2f",UserSession.getCurrentUserBalance());
        
        lBalance.setText(balance);
    }
    
    private void tfPayAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPayAmountKeyReleased

    }//GEN-LAST:event_tfPayAmountKeyReleased

    private void btnConfirmDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmDepositActionPerformed

        
        if (!tfPayAmount.getText().trim().isEmpty()){

            try {
                
                double depositAmount = Double.parseDouble(tfPayAmount.getText().trim());
                
                //POLYMORPHISM here
                PaymentGeneric paying = null;
                
                //here is the main part
                if (rbGeneric.isSelected()){
                    paying = new PaymentGeneric();
                    paying.pay(depositAmount);
                } else if (rbPaypal.isSelected()){
                    paying = new PaymentPaypal();
                    paying.pay(depositAmount);
                } else if (rbCard.isSelected()){
                    paying = new PaymentCard();
                    paying.pay(depositAmount);
                } else {
                    String errorMessage = "Please select a valid payment option!";
                    JOptionPane.showMessageDialog(null, errorMessage, "Deposit Failed", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                this.dispose();

            } catch (NumberFormatException e) {
                String errorMessage = "Invalid input, only numerical values are allowed.";
                JOptionPane.showMessageDialog(null, errorMessage, "Deposit Failed", JOptionPane.ERROR_MESSAGE);
                tfPayAmount.setText("00.00");
            }

        }

    }//GEN-LAST:event_btnConfirmDepositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pay().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmDeposit;
    private javax.swing.ButtonGroup groupPay;
    private javax.swing.JLabel lBalance;
    private javax.swing.JLabel lDepositAmount;
    private javax.swing.JLabel lDepositAmount1;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JRadioButton rbCard;
    private javax.swing.JRadioButton rbGeneric;
    private javax.swing.JRadioButton rbPaypal;
    private javax.swing.JTextField tfPayAmount;
    // End of variables declaration//GEN-END:variables
}
